baseURL = 'https://www.dailyremu.com/'
languageCode = 'ko-KR'
title = 'dailyremu'
theme = 'hugo-theme-stack'

[params]
  description = "매일 아침, 부동산 인사이트를 전합니다"
  mainSections = ["posts"]
  favicon = ""

  [params.sidebar]
    emoji = ""
    subtitle = "매일 아침, 부동산 인사이트"
    compact = false

  [params.article]
    math = false
    toc = true
    readingTime = true
    headingAnchor = false
    [params.article.list]
      showTags = true

  [params.footer]
    since = 2021
    customText = ""

  [[params.widgets.homepage]]
    type = "search"
  [[params.widgets.homepage]]
    type = "categories"
  [[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
      limit = 20
  [[params.widgets.page]]
    type = "toc"
  [[params.widgets.page]]
    type = "categories"

  [params.defaultImage]
    opengraph = ["featured", "cover", "thumbnail"]

  [params.colorScheme]
    toggle = true
    default = "auto"

[params.author]
  name = "dailyremu"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "홈"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "home"
  [[menu.main]]
    identifier = "categories"
    name = "카테고리"
    url = "/categories/"
    weight = 2
    [menu.main.params]
      icon = "categories"
  [[menu.main]]
    identifier = "tags"
    name = "태그"
    url = "/tags/"
    weight = 3
    [menu.main.params]
      icon = "tag"
  [[menu.main]]
    identifier = "search"
    name = "검색"
    url = "/page/search/"
    weight = 4
    [menu.main.params]
      icon = "search"
